{% set name = "goats" %}
{% set version = "25.6.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gemini-hlsw/goats/archive/{{ version }}.tar.gz
  sha256: 2c2ed83f86bdc526f1e88f0ab581403ad6d393f178b79608d79be0e38e6a15bc

build:
  entry_points:
    - goats = goats_cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true   # [win or arm64]
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - astropy >=6.0,<7
    - astroquery >=0.4.10
    - channels_redis >=4.2.1,<5
    - channels >=4.0,<5
    - click >=8.2.1,<9
    - django >=4.2.23,<5
    - django-cors-headers >=4.7.0,<5
    - django-dramatiq >=0.13.0
    - djangorestframework >=3.16.0,<4
    - dramatiq-abort >=1.2.1
    - dramatiq >=1.18.0,<2
    - marshmallow >=3.26.1,<4
    - marshmallow-jsonapi >=0.24.0
    - numpydoc >=1.8.0,<2
    - tomtoolkit >=2.24.5
    - dragons =4.0.0
    - redis-server >=7.2.8,<8
    - daphne >=4.2.0,<5
    - watchdog >=6.0.0,<7
    - redis-py >=6.2.0,<7

test:
  imports:
    - goats_tom
    - goats_cli
    - goats_setup
  commands:
    - pip check
    - goats --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gemini-hlsw/goats
  summary: Gemini Observation and Analysis of Targets System.
  license: CC0-1.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - src/goats_tom/static/fontawesome-free-6.7.2/LICENSE.txt
  doc_url: https://goats.readthedocs.io/en/{{ version }}/
  dev_url: https://github.com/gemini-hlsw/goats

extra:
  recipe-maintainers:
    - davner
    - soraisam
