{% set name = "goats" %}
{% set version = "26.4.4" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gemini-hlsw/goats/archive/{{ version }}.tar.gz
  sha256: a1662eb05668caaf0b7621d423adc002c95452b694727e2d39fbaf0f0bc5bb56

build:
  entry_points:
    - goats = goats_cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true   # [win or arm64]
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - apscheduler >=3.11.2,<4
    - astropy >=7
    - astroquery >=0.4.11
    - channels_redis >=4.3.0,<5
    - channels >=4.0,<5
    - click >=8.3.1,<9
    - django ==4.2.30,<5
    - django-cors-headers >=4.9.0,<5
    - django-dramatiq >=0.15.0
    - django-crispy-forms <2.6
    - djangorestframework >=3.16.1,<4
    - dramatiq-abort >=1.2.1
    - dramatiq >=1.18.0,<2
    - marshmallow ==3.26.1
    - marshmallow-jsonapi >=0.24.0
    - numpydoc >=1.9.0,<2
    - tomtoolkit ==2.31.6
    - dragons ==4.1.0
    - redis-server >=7.4.0,<8
    - daphne >=4.2.0,<5
    - watchdog >=6.0.0,<7
    - redis-py >=6.2.0,<7
    - gpp-client ==26.4.0
    - tom-tns >=0.3.4
test:
  imports:
    - goats_tom
    - goats_cli
    - goats_common
    - goats_setup
  commands:
#    - pip check
    - goats --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/gemini-hlsw/goats
  summary: Gemini Observation and Analysis of Targets System.
  license: CC0-1.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - src/goats_tom/static/fontawesome-free-6.7.2/LICENSE.txt
  doc_url: https://goats.readthedocs.io/en/{{ version }}/
  dev_url: https://github.com/gemini-hlsw/goats

extra:
  recipe-maintainers:
    - davner
    - soraisam
