name: Conda Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Conda build (${{ matrix.os }})Add commentMore actions
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13] # macos-13 = Intel-based runner
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
          channels: conda-forge, http://astroconda.gemini.edu/public
          channel-priority: strict
          conda-remove-defaults: "true"

      - name: Install build tools
        run: |
          conda install -y conda-build

      - name: Create output folder
        run: mkdir -p conda-artifacts

      - name: Build recipe
        run: |
          conda build goats-feedstock/recipe \
            --output-folder conda-artifacts \
            --channel conda-forge \
            --channel http://astroconda.gemini.edu/public \
            --override-channels \
            --no-anaconda-upload

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}--${{ runner.arch }}
          path: conda-artifacts/
          overwrite: true
