name: Test Slack Webhook

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: Nightly GOATS Conda install succeeded"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View run",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://google.com",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*OS:*\nCHANGE ME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Architecture:*\nCHANGE ME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Python Version:*\nCHANGE ME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Date:*\nCHANGE ME"
                    }
                  ]
                }
              ]
            }
