name: Test Conda Install

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC.

jobs:
  build_conda_env:
    name: Install and run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # Test building on Mac Intel as well.
        os: [ubuntu-latest, macos-13]
        python-version: ["3.12"]

    steps:
      - name: Install coreutils (macOS only)
        if: ${{ matrix.os == 'macos-13' }}
        run: brew install coreutils

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge, http://astroconda.gemini.edu/public, https://gemini-hlsw.github.io/goats-infra/conda
          channel-priority: strict
          conda-remove-defaults: "true"

      - name: Install GOATS from Conda channel
        run: conda install goats -y

      - name: Run setup in CI mode
        env:
          DJANGO_SUPERUSER_PASSWORD: changeme
        run: goats install --ci

      - name: Send Slack success
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: Nightly GOATS Conda install succeeded"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View run",
                      "emoji": true
                    },
                    "value": "view_run",
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*OS:*\n`${{ matrix.os }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Architecture:*\n`${{ runner.arch }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Python Version:*\n`${{ matrix.python-version }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Notify:*\n<@Dan Avner>"
                    },
                  ]
                }
              ]
            }


      - name: Send Slack failure
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":x: Nightly GOATS Conda install failed"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View run",
                      "emoji": true
                    },
                    "value": "view_run",
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*OS:*\n`${{ matrix.os }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Architecture:*\n`${{ runner.arch }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Python Version:*\n`${{ matrix.python-version }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Notify:*\n<@Dan Avner>"
                    },
                  ]
                }
              ]
            }
