name: Test Conda Install

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC.

jobs:
  build_conda_env:
    name: Install and run (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # Test building on Mac Intel as well.
        os: [ubuntu-latest, macos-13]
        python-version: ["3.12"]

    steps:
      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge, http://astroconda.gemini.edu/public, https://gemini-hlsw.github.io/goats-infra/conda
          channel-priority: strict
          conda-remove-defaults: "true"

      - name: Install GOATS from Conda channel
        run: conda install goats -y
