name: Test Slack Webhook

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
                "attachments": [
                {
                    "color": "#36a64f",              // green bar = success
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": ":white_check_mark: *Nightly GOATS Conda install succeeded*"
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                        {
                            "type": "button",
                            "text": {
                            "type": "plain_text",
                            "text": "View run logs",
                            "emoji": true
                            },
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "style": "primary"
                        }
                        ]
                    }
                    ]
                }
                ]
            }
